apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo-web-ingress
  namespace: forgejo
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`${FORGEJO_DOMAIN}`)
    kind: Rule
    services:
    - name: forgejo-http
      port: 3000