apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

resources:
  - ../../base/forgejo
  - secret.enc.yaml
  - db-credentials.enc.yaml
  - db-secret.enc.yaml
  - db-cluster.yaml
  - robots-configmap.yaml
  - release.yaml
  - ingress.yaml
  # - backup-secret.enc.yaml
  # - backup-schedule.yaml

configMapGenerator:
  - name: forgejo-prod-values
    namespace: forgejo
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml