# apps/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - gitea
  - forgejo
  - lemma
  - ghost
  - k9s-web
  - mail-backup
  - homelab-proxy
  - lute
