# /apps/prod/mail-backup/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail-backup

resources:
  - ../../base/mail-backup
  - restic-secret.enc.yaml
  - mbsync-secret.enc.yaml
  - mbsync-configmap.yaml
  - mbsync-cronjob.yaml
  - restic-cronjob.yaml
