apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec

resources:
  - namespace.yaml
  - lapi-secret.enc.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: crowdsec-prod-values
    namespace: crowdsec
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
