# /apps/prod/headlamp/ingress.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`${HEADLAMP_DOMAIN}`)
    kind: Rule
    middlewares:
      - name: auth-authelia@kubernetescrd
    services:
    - name: headlamp
      port: 80
      namespace: headlamp
