# /apps/prod/headlamp/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp

resources:
  - ../../base/headlamp
  - release.yaml
  - ingress.yaml
  - service-account.yaml

configurations:
  - kustomizeconfig.yaml
