apiVersion: v1
kind: Service
metadata:
  name: homelab-proxy
  namespace: homelab-proxy
  annotations:
    tailscale.com/tailnet-fqdn: ${HOMELAB_TAILNET_FQDN}
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: ${HOMELAB_INTERNAL_PORT}
      name: http
