# infrastructure/controllers/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb
  - cert-manager
  - traefik
  - tailscale
  - crowdsec
  - k8up
  - cloudnative-pg
