apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: crowdsec-bouncer
    namespace: crowdsec
spec:
    plugin:
        crowdsec-bouncer-traefik-plugin:
            enabled: ENC[AES256_GCM,data:mFkGSQ==,iv:8Ny4w6TFBwGGpkUjpVEYsxl9+ApOJwzFbVUZl+ZfXN0=,tag:xo5pPyB6NlNdbicRW6sKyQ==,type:bool]
            logLevel: ENC[AES256_GCM,data:J+1chA==,iv:Vq7eJ5HoMBlLfQc27MhOokCtpW6931IkWv61VKHNRQc=,tag:2sRTBkhv3lKgeoiwud18ag==,type:str]
            crowdsecMode: ENC[AES256_GCM,data:gp7WGQ==,iv:BYVINu7w0JIz8cp6IDYaYbIAdjLu3L5eYB1SzHLgJSI=,tag:2gyRHrZ4VFCG9vwQRZHP8A==,type:str]
            crowdsecLapiScheme: ENC[AES256_GCM,data:BSlF0A==,iv:jUjd5uEAwQkfat9ehfJczohj/glP5iv7ksdAOtTuXBw=,tag:SlbUCEgi1b+/kBUdowZ6Bg==,type:str]
            crowdsecLapiHost: ENC[AES256_GCM,data:7+aEtqqKZ8HncF063dQYDC5/i5Ejw2CfEMLmKWybktP4lDq9E0gmgbLMVo/m0ifJ,iv:WvSS5+KzO7Cq5tlatAWZzauLFa++0BqekX5UUzDOi/c=,tag:l4t4ZezhNyhP1l7Emk10hw==,type:str]
            crowdsecLapiKey: ENC[AES256_GCM,data:0ITs1o9cCqaqSkSpntFcfr4TaJktcMGyiF6YAHToFW+aBFal/61QXlctIQ==,iv:AqCuLEF36BkmO0oo7ftIvMP1+X+/f1kUEt5RQPKcvCI=,tag:kADPZ2IXLHHDirCQWH4rKQ==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcVRVbHEraTZ4VEs5dWc5
            c0V5N0tCbjBTQXAvcXFDc0JYcUlNK2ZEWW1vCm9NQmJ0R1NHRWxTdnNhdWIwelF1
            Yy91UE1sU1ZlTC9CM3A4NXdIeVdsS00KLS0tIGVCaVFLVkxFWWZYNTc1S3ArNnNI
            M0RJTU54OTZqbzRmTXZ6aUpkYy94U2cK/MA1r0zHVkEEOgTeiQMSw3Vu/Kinvrcc
            Z86y93kkBM5hLZDJcCQg4OkxrDmrLCLD8ohQXQ99+Jp08Zo1W0JxrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T22:35:03Z"
    mac: ENC[AES256_GCM,data:H/r3iBloJrRuq0ESExvRympfUduStg2Lis7Ur9gV6gMUKVbHjXaycyKlKcih5d5QgKYnfNxri3mhy1cTuySinKCBUcDH00+B1vThdPcFRnV2KpPUMPz7Md/SnrzW0PgNKFWeR7P/xt08kJrgMkHtKyr4sBov0DCtNA30mK6ZZAk=,iv:jYaXnieF4oeA4MUZVBQUPqVRWD7BeLI/3Cmu8Bzagcs=,tag:AjtEKV8xy1+GpuRAolmAFg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
