#ENC[AES256_GCM,data:qB3Ii7aIlqSeTdkWDREHjDIxar75mLVA5UtR/nX1LUh1tv3XHf9PmJEmHB+adwReRf091GY=,iv:ZoHEiy57GFlARcDTSm0wcBHizie0KiJ6f+En1V8PRF0=,tag:a4pyCJzVlWSyNQtCfCvuPA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret-main
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:dJI9HeNINziKPYlmY4DVneNPTZ+lJkOX9d4BvbdqLNterIHiiDmjwg==,iv:uuozutD9Y6bbw9BaMMq6UZTYLnnhZf4tDFPPWpvW1Iw=,tag:Wt6XvR5DpO1ivEcic30b2A==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMUpDWmJJbmpvdEhlVlRN
            amlvaGhVYUVzTVUycGFTZmRBeHo4NUkzYjJrCjc4QzRxa09PYnM2STlaSlh4VDB4
            R0Nud1hCb29WSW9ETW4yamlqdDNXRlkKLS0tICtuTUN3WGpQMjNzemNrQitFUGpp
            WDBXM0JsN1pJSW5YV3BUcTZDVDhHdjgKMAv3Jl4rWGvcxWliTj6sXelYXKR6V4H/
            fFI/92uZ9LdawsnZR8B2tPF3dLkZ6WAgm0Wc2WT9lMqtVjNHgaeDMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:49:38Z"
    mac: ENC[AES256_GCM,data:7KZBmkKZAnVrVMOZM+JeqRuyfVMWJv6vISGcwdXjZXMOLmjTYRWyItMqyj04h/AJscTWWsnS2sRkVt78xLpJ1G90OzT2+oQgMbi72OascZHJIdGc0iDkJuTsI28soEDuPorVJojwnrATvDkGdAgyuAd3e9AsjRxFWnMaCyfXoXw=,iv:FN1tzA9KsBs+J67xw91dD1DFo7kOmdFt5LsncmxRWJY=,tag:tWJ5lzDzOVRzIHNkbTJhLg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret-secondary
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:yMcc7uGVAKfpuShI2H5P7cvEzgnbvyvNGGyMzsfwGIEgKD9dP2ZeKQ==,iv:p6N/6gWgQ8Cm3w+E79r+A4kBEXUBNPpaS6lucNFIMdg=,tag:Pw699DhPLekmSExoA36QPA==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMUpDWmJJbmpvdEhlVlRN
            amlvaGhVYUVzTVUycGFTZmRBeHo4NUkzYjJrCjc4QzRxa09PYnM2STlaSlh4VDB4
            R0Nud1hCb29WSW9ETW4yamlqdDNXRlkKLS0tICtuTUN3WGpQMjNzemNrQitFUGpp
            WDBXM0JsN1pJSW5YV3BUcTZDVDhHdjgKMAv3Jl4rWGvcxWliTj6sXelYXKR6V4H/
            fFI/92uZ9LdawsnZR8B2tPF3dLkZ6WAgm0Wc2WT9lMqtVjNHgaeDMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:49:38Z"
    mac: ENC[AES256_GCM,data:7KZBmkKZAnVrVMOZM+JeqRuyfVMWJv6vISGcwdXjZXMOLmjTYRWyItMqyj04h/AJscTWWsnS2sRkVt78xLpJ1G90OzT2+oQgMbi72OascZHJIdGc0iDkJuTsI28soEDuPorVJojwnrATvDkGdAgyuAd3e9AsjRxFWnMaCyfXoXw=,iv:FN1tzA9KsBs+J67xw91dD1DFo7kOmdFt5LsncmxRWJY=,tag:tWJ5lzDzOVRzIHNkbTJhLg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
